### ISSUE TITLE
Short question about the scope of this project

### ISSUE THREAD

**Issue by donaldpipowitch** [bradzacher/eslint-plugin-typescript#243]
Hi,

something I couldn't real figure out from the README is the correct scope of the project. (Maybe this is an interesting question to answer before the `1.0.0` release? https://github.com/bradzacher/eslint-plugin-typescript/issues/151)

1. Is this project about _"just"_ adding TypeScript support to the default ESLint configs and rules? (E.g. like `typescript/no-unused-vars -> Prevent TypeScript-specific constructs from being erroneously flagged as unused`)
2. Is this project about _enhancing_ ESLint rules with TypeScript? (E.g. `no-unused-vars` is not fixable in ESLint and [I currently prototype a custom rule which _is_ fixable and uses the TypeScript language server](https://github.com/donaldpipowitch/experiments/tree/master/eslint-custom-no-unused-var). Could that be something I can add to this project via a Pull Request potentially?)
3. Can I build custom rules _upon_ this project? (E.g. as I mentioned my custom rule creates a TypeScript language server and it would be nice if a framework/plugin like this one could do that for me, so I don't need to reinvent the wheel.)

Thank you :)

**Comment by j-f1** [comment]
I think `typescript-eslint-parser` will soon be providing access to the TypeScript instance.

I guess this plugin is for both feature parity with TSLint and any TypeScript-specific rules.

**Comment by bradzacher** [comment]
Essentially this project exists for all of the above.

- We are adding support to the base eslint rules for the TS AST produced by `typescript-eslint-parser`, thus enabling the use of eslint with TS.
    - see indent, no-unused-vars, camelcase
- We are building new, custom rules to add linting around typescript specific language features.
    - see array-type, no-object-literal-type-assertion, prefer-interface, etc


The reason we talk about TSLint so much is because they are a project that is "doing the same thing as us" (except outside of ESLint). They have been a lot more active for the last year or two; so they have a lot of rules for us to implement here. Feature parity isn't an *explicit* goal, but it certainly is a motivator because they do some great stuff, and feature parity puts us in a very good place.


As for building rules with type information. It's certainly on our roadmap. We have talked about it internally. We're not sure what rules we'll add or how we'll make them work, but it's all part of a very exciting future.


In regards to a `no-unused-vars` fixer. This is a difficult thing to do without annoying users, esp with things like IDEs and prettier-eslint providing the ability to run eslint fixers automatically on save.
Most developers don't like fixers which can physically effect their development workflow; and having purposely undefined variables is a big part of half finished code
That would be why tslint deprecated their fixer, and [is why `no-debugger` had its fixer *removed*.](https://github.com/eslint/eslint/issues/10242). It's not because it's hard to implement/maintain - it's because people get annoyed by it, and the tooling provides no good way to disable specific fixers; meaning people turn the rule off.

**Comment by donaldpipowitch** [comment]
Thank you both for the answers!

> I think `typescript-eslint-parser` will soon be providing access to the TypeScript instance.

With _TypeScript instance_ do you mean an instance of the language server? That would be awesome as I need access to `getSuggestionDiagnostics`.

> Feature parity isn't an _explicit_ goal, but it certainly is a motivator because they do some great stuff, and feature parity puts us in a very good place.

Sounds awesome. I, too, want to drop TSLint, so I can focus on one tool (and maybe create custom rules for _one_ tool instead of two). I also don't _need_ absolute feature parity, but the more the better.

> This is a difficult thing to do without annoying users ... That would be why tslint deprecated their fixer, 

I always thought TSLint deprecated it, because it was too hard to maintain (I don't know why they haven't tried to use `getSuggestionDiagnostics` and re-implemented the logic on their own, though.) 🤔 All in all that sounds a little bit more like a tooling problem, so we can have two configs (or express this in one config with more options) to fix _some_ rules on save and others in other cases (e.g. on commit, on release, etc.).

Also from the linked `no-debugger` ticket: If the rule is _"As I recall, the guideline for autofixers is that they shouldn't change the execution of the code."_ a `no-unused-vars` should probably be okay...?

Would _you_ include a `no-unused-vars` fixer?

**Comment by bradzacher** [comment]
> I always thought TSLint deprecated it, because it was too hard to maintain

I wouldn't have thought this was the case. If you know the variable is unused, it's trivial to remove it; the AST tells you exactly where the declaration starts and finishes. The fixer doesn't even have to worry about newlines and such, as other fixers will take care of that.

If the fixer was hard to maintain, then the rule itself is hard to maintain (which is a lot more true - just look at the source for [eslint's `no-unused-vars` rule](https://github.com/eslint/eslint/blob/master/lib/rules/no-unused-vars.js); it's a 700 line monster.

> All in all that sounds a little bit more like a tooling problem

It definitely is. Being able to disable certain fixers is probably a good feature. It's probably a bit of a can-of-worms though in terms of implementation and support.
Configs would disable certain fixers then people would wonder why things don't fix, you'd have to add ide support for detecting if fixers are on/off, people would want to disable a set of fixers within a rule, etc.

> Would you include a no-unused-vars fixer?

I personally wouldn't include a fixer.

I'm of the opinion that you shouldn't automatically fix semantic "problems" with someone's code. If they have an unused variable and you auto fix it at commit time (or on a CI server), then potentially you've just hidden the fact that they've forgotten to implement something, and then your feature launches and breaks in production.
It's much better to thrown an error and let the engineer figure out if it should be safely deleted, or if it's a missing feature.

Also leads back to the fix on save integration as well. A lot of users of this plugin use `no-unused-vars` so that they can have non-build-blocking warnings of unused vars (TS's implementation blocks the build). If it's on so that their IDE flags the unused var, then their IDE will also remove the unused var on save.
